Repository pwa-builder/PWABuilder, pull requests merged in 2023-08, with the labels that each got.

#4148 Tokens Flow
  .github/workflows/pwabuilder-preview.yml
  .gitignore
  apps/blog/src/posts/introducing-the-brand-new-pwa-builder/introducing-the-brand-new-pwa-builder.md
  apps/blog/src/posts/manifest-previewer/manifest-previewer.md
  apps/pwabuilder/package-lock.json
  apps/pwabuilder/package.json
  apps/pwabuilder/public/assets/congrats-manny-mobile.png
  apps/pwabuilder/public/assets/copy_icon_darkgrey.svg
  apps/pwabuilder/public/assets/microsoft-promo-banner.png
  apps/pwabuilder/public/assets/microsoft_store_icon_white.png
  apps/pwabuilder/public/assets/new/colorful-logo.svg
  apps/pwabuilder/public/assets/new/discord.svg
  apps/pwabuilder/public/assets/new/giveaway_banner_mobile.png
  apps/pwabuilder/public/assets/new/giveaway_banner_nourl.png
  apps/pwabuilder/public/assets/new/giveaway_banner_nourl_1920.png
  apps/pwabuilder/public/assets/new/giveaway_banner_url.png
  apps/pwabuilder/public/assets/new/left-arrow.svg
  apps/pwabuilder/public/assets/new/macro_passed.svg
  apps/pwabuilder/public/assets/new/marketing-img1.png
  apps/pwabuilder/public/assets/new/marketing-img2-mobile.png
  apps/pwabuilder/public/assets/new/marketing-img2.png
  apps/pwabuilder/public/assets/new/msft-logo-giveaway.svg
  apps/pwabuilder/public/assets/new/msft_store_giveaway.svg
  apps/pwabuilder/public/assets/new/twitter.svg
  apps/pwabuilder/public/assets/new/yellow_exclamation.svg
  apps/pwabuilder/public/assets/token_code_bg_image.png
  apps/pwabuilder/public/assets/white-arrow.png
  apps/pwabuilder/src/app-index.ts
  apps/pwabuilder/src/script/components/arrow-link.ts
  apps/pwabuilder/src/script/components/publish-pane.ts
  apps/pwabuilder/src/script/components/todo-list-item.ts
  apps/pwabuilder/src/script/pages/app-report.ts
  apps/pwabuilder/src/script/pages/qualification/app-token.helper.ts
  apps/pwabuilder/src/script/pages/qualification/app-token.style.ts
  apps/pwabuilder/src/script/pages/qualification/app-token.template.ts
  apps/pwabuilder/src/script/pages/qualification/app-token.ts
  apps/pwabuilder/src/script/pages/qualification/token-congratulations.style.ts
  apps/pwabuilder/src/script/pages/qualification/token-congratulations.ts
  apps/pwabuilder/src/script/services/auth_service.ts
  apps/pwabuilder/src/script/utils/environment.ts
  apps/pwabuilder/styles/global.css
  apps/pwabuilder/tsconfig.json
  components/code-editor/package-lock.json
  components/manifest-editor/src/components/manifest-info-form.ts
  components/manifest-editor/src/components/manifest-platform-form.ts
  components/manifest-previewer/README.md
  libraries/manifest-information/src/index.ts
Labels: DO-NOT-MERGE

#4245 [DOCS][TOKEN] 4203: Token Doc
  docs/assets/builder/store-promotion/promo-registration-info.png
  docs/assets/builder/store-promotion/promo-registration-payment.png
  docs/assets/builder/store-promotion/tests-passed.png
  docs/assets/builder/store-promotion/token-action-item.png
  docs/assets/builder/store-promotion/view-token-code.png
  docs/builder/store-promotion.md
  docs/release-notes/2023.md
  docs/src/menuData.ts
Labels: documentation, DO-NOT-MERGE

#4264 Gleb/tokens blog
  apps/blog/src/posts/free-dev-account/free-account-pic-1.jpg
  apps/blog/src/posts/free-dev-account/free-account-pic-2.jpg
  apps/blog/src/posts/free-dev-account/free-account-pic-3.jpg
  apps/blog/src/posts/free-dev-account/free-dev-account.md
Labels: DO-NOT-MERGE

#4216 [DOCS][TOKEN] Added Draft of Banner for Token promotion
  docs/README.md
  docs/index.html
  docs/styles/global.css
Labels: documentation, DO-NOT-MERGE

#4167 [DOCS] #4123: Benefits of PWA article
  docs/home/benefits-of-pwa.md
Labels: documentation

#4328 [Accessibility] Fix to radios and checkboxes not being associated with their labels
  apps/pwabuilder/src/script/pages/image-generator.ts
Labels: DO-NOT-MERGE
