Repository pwa-builder/PWABuilder, pull requests merged in 2023-06, with the labels that each got.

#4122 [DOCS] Added clarity about updating to FAQ and to quick start for pwabuilder
  docs/builder/faq.md
  docs/builder/quick-start.md
Labels: documentation

#4080 manifest-validation refined and npm'ed
  .github/workflows/manifest-validation-npm.yml
  apps/pwabuilder/package-lock.json
  apps/pwabuilder/public/assets/manifest_examples/display_override_example_image.jpg
  apps/pwabuilder/public/assets/manifest_examples/display_override_example_image.png
  apps/pwabuilder/public/assets/manifest_examples/file_handlers_example_image.jpg
  apps/pwabuilder/public/assets/manifest_examples/file_handlers_example_image.png
  apps/pwabuilder/public/assets/manifest_examples/iarc_example_image.jpg
  apps/pwabuilder/public/assets/manifest_examples/iarc_example_image.png
  apps/pwabuilder/public/assets/manifest_examples/shortcuts_example_image.jpg
  apps/pwabuilder/public/assets/manifest_examples/shortcuts_example_image.png
  apps/pwabuilder/src/script/pages/app-report.ts
  components/manifest-editor/package-lock.json
  libraries/manifest-information/src/index.ts
  libraries/manifest-validation/README.md
  libraries/manifest-validation/package-lock.json
  libraries/manifest-validation/package.json
  libraries/manifest-validation/src/index.ts
  libraries/manifest-validation/src/interfaces.ts
  libraries/manifest-validation/src/locales/locales.ts
  libraries/manifest-validation/src/mani-tests.ts
  libraries/manifest-validation/src/utils/validation-utils.ts
  libraries/manifest-validation/src/utils/values-schema.ts
  libraries/manifest-validation/src/validations.ts
  libraries/manifest-validation/test/test-manifest.json
  libraries/manifest-validation/test/validation-tests.mjs
  libraries/manifest-validation/tsconfig.json
Labels: Validation Lib

#4081 report-card apiv2 use
  apps/pwabuilder/.mocharc.json
  apps/pwabuilder/package-lock.json
  apps/pwabuilder/package.json
  apps/pwabuilder/src/script/components/todo-list-item.ts
  apps/pwabuilder/src/script/pages/app-report.api.ts
  apps/pwabuilder/src/script/pages/app-report.helper.ts
  apps/pwabuilder/src/script/pages/app-report.ts
  apps/pwabuilder/src/script/services/congrats.ts
  apps/pwabuilder/src/script/services/download_icons.ts
  apps/pwabuilder/src/script/services/manifest.ts
  apps/pwabuilder/src/script/services/publish/web-publish.ts
  apps/pwabuilder/src/script/services/tests/index.ts
  apps/pwabuilder/src/script/services/tests/manifest.ts
  apps/pwabuilder/src/script/services/tests/security.ts
  apps/pwabuilder/src/script/services/tests/service-worker.ts
  apps/pwabuilder/src/script/utils/environment.ts
  apps/pwabuilder/src/script/utils/interfaces.ts
  components/manifest-editor/package-lock.json
  components/manifest-editor/src/components/manifest-share-form.ts
  libraries/manifest-validation/package-lock.json
  libraries/manifest-validation/src/index.ts
  libraries/manifest-validation/src/mani-tests.ts
Labels: DO-NOT-MERGE

#4094 Staging -> Main
  .github/workflows/manifest-validation-npm.yml
  apps/pwabuilder/package-lock.json
  apps/pwabuilder/public/assets/manifest_examples/display_override_example_image.jpg
  apps/pwabuilder/public/assets/manifest_examples/display_override_example_image.png
  apps/pwabuilder/public/assets/manifest_examples/file_handlers_example_image.jpg
  apps/pwabuilder/public/assets/manifest_examples/file_handlers_example_image.png
  apps/pwabuilder/public/assets/manifest_examples/iarc_example_image.jpg
  apps/pwabuilder/public/assets/manifest_examples/iarc_example_image.png
  apps/pwabuilder/public/assets/manifest_examples/shortcuts_example_image.jpg
  apps/pwabuilder/public/assets/manifest_examples/shortcuts_example_image.png
  apps/pwabuilder/public/assets/minus.svg
  apps/pwabuilder/public/assets/plus.svg
  apps/pwabuilder/src/script/components/manifest-info-card.ts
  apps/pwabuilder/src/script/components/todo-list-item.ts
  apps/pwabuilder/src/script/pages/app-report.ts
  apps/pwabuilder/src/script/services/publish/windows-publish.ts
  apps/pwabuilder/src/script/utils/service-workers/service-workers.ts
  components/manifest-editor/package-lock.json
  components/manifest-editor/src/components/manifest-field-tooltip.ts
  components/manifest-editor/src/components/manifest-icons-form.ts
  components/manifest-editor/src/components/manifest-platform-form.ts
  components/manifest-editor/src/components/manifest-share-form.ts
  components/manifest-editor/src/components/pwa-manifest-editor.ts
  components/manifest-editor/src/components/search-extensions.ts
  components/manifest-editor/src/utils/extensions.ts
  docs/home/pwa-workshop.md
  docs/release-notes/2023.md
  libraries/manifest-information/src/index.ts
  libraries/manifest-validation/README.md
  libraries/manifest-validation/package-lock.json
  libraries/manifest-validation/package.json
  libraries/manifest-validation/src/index.ts
  libraries/manifest-validation/src/interfaces.ts
  libraries/manifest-validation/src/locales/locales.ts
  libraries/manifest-validation/src/mani-tests.ts
  libraries/manifest-validation/src/utils/validation-utils.ts
  libraries/manifest-validation/src/utils/values-schema.ts
  libraries/manifest-validation/src/validations.ts
  libraries/manifest-validation/test/test-manifest.json
  libraries/manifest-validation/test/validation-tests.mjs
  libraries/manifest-validation/tsconfig.json
Labels: to review :book:

#4143 [DOCS] Corrected inaccuracy around adding cert for iOS packaging
  docs/builder/app-store.md
Labels: documentation

#4153 [SITE] 4149: Only Add retest notification once for each category
  apps/pwabuilder/src/script/pages/app-report.ts
Labels: site

#4159 [DOCS] 4158: Minor manifest reference fixes
  docs/builder/manifest.md
Labels: documentation

#4160 [DOCS] 4141: Related applications instruction for Windows and Android
  docs/builder/faq.md
Labels: documentation
